test:
  adapter: postgresql
  database: pl_test
  encoding: unicode
  host: localhost

development:
  adapter: postgresql
  database: pl_dev
  encoding: unicode
  host: localhost

production:
  url: <%= ENV['DATABASE_URL'] %>
