test:
  adapter: postgresql
  database: pl_test
  encoding: unicode
  host: localhost

development:
  adapter: postgresql
  database: pl_dev
  encoding: unicode
  host: localhost

production:
  adapter: postgresql
  database: pl_prod
  encoding: unicode
  host: localhost
  username: rails
  password: <%= ENV['DB_PASS'] %>
